name: CI/CD

on:
  push:
  pull_request:

jobs:
  lint-and-unit-tests:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install flake8 pytest

      - name: Lint all Python in backend and tests
        run: |
          flake8 backend tests

      - name: Run all tests
        run: |
          pytest tests --maxfail=1 --disable-warnings -q

  build-and-push:
    name: Build & Push Docker image
    needs: lint-and-unit-tests
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push'
        && (github.ref == 'refs/heads/main'
            || github.ref == 'refs/heads/alekseevpy')
      )
      || (github.event_name == 'pull_request')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            alekseevpy/whalesdetection-api:latest
            alekseevpy/whalesdetection-api:${{ github.sha }}